name: Create Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.13.8"

      - run: go build -o isogo_darwin_386
        env:
          GOOS: "darwin"
          GOARCH: "386"
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v1
        with:
          name: isogo_darwin_386
          path: isogo_darwin_386

      - run: go build -o isogo_darwin_amd64
        env:
          GOOS: "darwin"
          GOARCH: "amd64"
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v1
        with:
          name: isogo_darwin_amd64
          path: isogo_darwin_amd64

      - run: go build -o isogo_linux_386
        env:
          GOOS: "linux"
          GOARCH: "386"
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v1
        with:
          name: isogo_linux_386
          path: isogo_linux_386

      - run: go build -o isogo_linux_amd64
        env:
          GOOS: "linux"
          GOARCH: "amd64"
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v1
        with:
          name: isogo_linux_amd64
          path: isogo_linux_amd64

      - run: go build -o isogo_windows_386
        env:
          GOOS: "windows"
          GOARCH: "386"
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v1
        with:
          name: isogo_windows_386
          path: isogo_windows_386

      - run: go build -o isogo_windows_amd64
        env:
          GOOS: "windows"
          GOARCH: "amd64"
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v1
        with:
          name: isogo_windows_amd64
          path: isogo_windows_amd64

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_id }}_${{ github.run_number }}
          release_name: Release ${{ github.run_id }}_${{ github.run_number }}
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v1
        with:
          name: isogo_darwin_386

      - uses: actions/download-artifact@v1
        with:
          name: isogo_darwin_amd64

      - uses: actions/download-artifact@v1
        with:
          name: isogo_linux_386

      - uses: actions/download-artifact@v1
        with:
          name: isogo_linux_amd64

      - uses: actions/download-artifact@v1
        with:
          name: isogo_windows_386

      - uses: actions/download-artifact@v1
        with:
          name: isogo_windows_amd64

      - name: Upload Release Assets - Darwin 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: isogo_darwin_386/isogo_darwin_386
          asset_name: isogo_darwin_386
          asset_content_type: application/octet-stream


      - name: Upload Release Assets - Darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: isogo_darwin_amd64/isogo_darwin_amd64
          asset_name: isogo_darwin_amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Linux 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: isogo_linux_386/isogo_linux_386
          asset_name: isogo_linux_386
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: isogo_linux_amd64/isogo_linux_amd64
          asset_name: isogo_linux_amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Windows 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: isogo_windows_386/isogo_windows_386
          asset_name: isogo_windows_386
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Windows amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: isogo_windows_amd64/isogo_windows_amd64
          asset_name: isogo_windows_amd64
          asset_content_type: application/octet-stream
